version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: "monthly"
    groups:
      go:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: "monthly"
    groups:
      go:
        patterns:
          - "*"
